using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.SqlClient;
using System.Text;
using System.Diagnostics;
using System.Web.UI;
using SQL = System.Data.SqlClient;
using System.Collections;


namespace CAIRS
{
    public class Constants
    {
        public static string APPID_MCS_ADMIN = "1";
        //APP Environments
        //Environments
        public static string ENVIRONMENT_PROD = "PRODUCTION";
        public static string ENVIRONMENT_QA = "QA";
        public static string ENVIRONMENT_DEV = "DEVELOPMENT";
        //DB SERVER
        public static string DB_SERVER_PROD = "reno-sqlis";
        public static string DB_SERVER_QA = "reno-sqlqa";
        //NULL Values
        public static string MCSDBNULL = "::DBNULL::";

        /// <summary>
        /// This is used for upsert method (ExecuteStoredProcUpsert) to prevent updating a given column.
        /// </summary>
        public static string MCSDBNOPARAM = "::NOPARAM::";

        //ADD ASSET TYPE
        public static string ADD_ASSET_TYPE_SCAN = "SCAN";
        public static string ADD_ASSET_TYPE_UPLOAD = "UPLOAD";

        //RECORD TYPES
        #region Security Record Type
        public const string SECURITY_RECORDTYPE_SECURITY_VIOLATION = "1";
        public const string SECURITY_RECORDTYPE_APPLICATION_ERROR = "2";
        public const string SECURITY_RECORDTYPE_USER_ERROR = "3";
        public const string SECURITY_RECORDTYPE_STANDARD_OPERATION = "4";
        

        public const string CAIRS_APP_MODULE_ACCESS_DENIED = "Unauthorized Access";
        public const string CAIRS_APP_MODULE_SEND_EMAIL = "Send Email";

        #endregion

        //Standard Option Selection
        #region Option Selection
        public const string _OPTION_PLEASE_SELECT_VALUE = "-1";
        public const string _OPTION_PLEASE_SELECT_TEXT = "--- Select "; // leave end space for concatenation
        public const string _OPTION_ALL_VALUE = "-99";
        public const string _OPTION_ALL_TEXT = "--- All ";
        public const string _OPTION_NO_DATA_FOUND_VALUE = "-2";
        public const string _OPTION_NO_DATA_FOUND_TEXT = "--- NO DATA FOUND ---";
        public const string _OPTION_SELECT_SITE_VALUE = "-1";
        public const string _OPTION_SELECT_SITE_TEXT = "--- Select Site to populate ---";
        #endregion

        //Database Names
        #region Database Names
        public const string DBNAME_ASSET_TRACKING = "Asset_Tracking";
        public const string DBNAME_DATAWAREHOUSE = "Datawarehouse";
        public const string DBNAME_SECURITY = "Security";
        public const string DBNAME_MCS = "MCS";
        #endregion

        //CAIRS Table Names 64
        #region Asset_Tracking Table Name
        public static string TBL_APP_ACTIVITY = "App_Activity";
        public static string TBL_APP_PREFERENCE_TYPE = "App_Preference_Type";
        public static string TBL_APP_USER_PREFERENCE = "App_User_Preference";
        public static string TBL_ASSET = "Asset";
        public static string TBL_ASSET_ATTACHMENT = "Asset_Attachment";
        public static string TBL_ASSET_BIN_MAPPING = "Asset_Bin_Mapping";
        public static string TBL_ASSET_CHECKOUT_EXCEPTION_STUDENT_DETAIL = "Asset_CheckOut_Exception_Student_Detail";
        public static string TBL_ASSET_CHECKOUT_EXCEPTION_STUDENT_HEADER = "Asset_CheckOut_Exception_Student_Header";
        public static string TBL_ASSET_COMMENT = "Asset_Comment";
        public static string TBL_ASSET_LAW_ENFORCEMENT = "Asset_Law_Enforcement";
        public static string TBL_ASSET_LOAD = "Asset_Load";
        public static string TBL_ASSET_REPAIR = "Asset_Repair";
        public static string TBL_ASSET_SEARCH = "Asset_Search";
        public static string TBL_ASSET_SEARCH_DETAIL = "Asset_Search_Detail";
        public static string TBL_ASSET_SITE_MAPPING = "Asset_Site_Mapping";
        public static string TBL_ASSET_SITE_STORED_MAPPING = "Asset_Site_Stored_Mapping";
        public static string TBL_ASSET_STUDENT_FEE = "Asset_Student_Fee";
        public static string TBL_ASSET_STUDENT_NOTIFICATION = "Asset_Student_Notification";
        public static string TBL_ASSET_STUDENT_TRANSACTION = "Asset_Student_Transaction";
        public static string TBL_ASSET_STUDENT_TRANSACTION_INTERACTION = "Asset_Student_Transaction_Interaction";
        public static string TBL_ASSET_TAMPER = "Asset_Tamper";
        public static string TBL_ASSET_TEMP_DETAIL = "Asset_Temp_Detail";
        public static string TBL_ASSET_TEMP_HEADER = "Asset_Temp_Header";
        public static string TBL_AUDIT_LOG = "Audit_Log";
        public static string TBL_BIN = "Bin";
        public static string TBL_BUSINESS_RULE = "Business_Rule";
        public static string TBL_BUSINESS_RULE_DETAIL = "Business_Rule_Detail";
        public static string TBL_CT_ASSET_ASSIGNMENT_TYPE = "CT_Asset_Assignment_Type";
        public static string TBL_CT_ASSET_BASE_TYPE = "CT_Asset_Base_Type";
        public static string TBL_CT_ASSET_CONDITION = "CT_Asset_Condition";
        public static string TBL_CT_ASSET_DISPOSITION = "CT_Asset_Disposition";
        public static string TBL_CT_ASSET_TYPE = "CT_Asset_Type";
        public static string TBL_CT_CHECK_IN_TYPE = "CT_Check_In_Type";
        public static string TBL_CT_DEVICE_FEE_TYPE = "CT_Device_Fee_Type";
        public static string TBL_CT_FILE_TYPE = "CT_File_Type";
        public static string TBL_CT_INTERACTION_TYPE = "CT_Interaction_Type";
        public static string TBL_CT_LAW_ENFORCEMENT_AGENCY = "CT_Law_Enforcement_Agency";
        public static string TBL_CT_NOTIFICATION_TYPE = "CT_Notification_Type";
        public static string TBL_CT_REPAIR_TYPE = "CT_Repair_Type";
        public static string TBL_CT_SITE = "CT_Site";
        public static string TBL_CT_VENDOR = "CT_Vendor";
        public static string TBL_REPORTS = "Reports";
        public static string TBL_STUDENT_DEVICE_COVERAGE = "Student_Device_Coverage";
        public static string TBL_STUDENT_DEVICE_FEE_SCHEDULE = "Student_Device_Fee_Schedule";
        public static string TBL_SYSDIAGRAMS = "sysdiagrams";
        public static string TBL_V_ADD_ASSET_PREVIOUS_BATCH = "v_Add_Asset_Previous_Batch";
        public static string TBL_V_ASSET_BIN = "v_Asset_Bin";
        public static string TBL_V_ASSET_INFO_CHECKIN = "v_Asset_Info_CheckIn";
        public static string TBL_V_ASSET_LAW_ENFORCEMENT = "v_Asset_Law_Enforcement";
        public static string TBL_V_ASSET_MASTER_LIST = "v_Asset_Master_List";
        public static string TBL_V_ASSET_STUDENT_ASSGINMENT = "v_Asset_Student_Assginment";
        public static string TBL_V_ASSET_TAB_ASSGINMENT = "v_Asset_Tab_Assginment";
        public static string TBL_V_ASSET_TAB_ATTACHMENTS = "v_Asset_Tab_Attachments";
        public static string TBL_V_ASSET_TAB_CHANGES = "v_Asset_Tab_Changes";
        public static string TBL_V_ASSET_TAB_COMMENTS = "v_Asset_Tab_Comments";
        public static string TBL_V_ASSET_TAB_REPAIRS = "v_Asset_Tab_Repairs";
        public static string TBL_V_ASSET_TAB_TAMPER = "v_Asset_Tab_Tamper";
        public static string TBL_V_ASSET_TEMP_HEADER_DETAIL = "v_Asset_Temp_Header_Detail";
        public static string TBL_V_BIN = "v_Bin";
        public static string TBL_V_STUDENT_ASSET_SEARCH = "v_Student_Asset_Search";
        public static string TBL_V_STUDENT_CHECKIN_NO_TAG_ID = "v_Student_CheckIn_No_Tag_ID";
        public static string TBL_V_STUDENT_COVERAGE = "v_Student_Coverage";
        public static string TBL_V_STUDENT_CURRENT_ASSIGNMENT = "v_Student_Current_Assignment";
        public static string TBL_V_USER_SECURITY_INFO = "v_User_Security_Info";

        #endregion

        //Security Table Name
        #region Security.dbo.Table Name
        public static string SECURITY_TBL_APPLICATIONEXCEPTIONS = "ApplicationExceptions";
        #endregion

        //CAIRS ColumnNames 782
        #region Asset_Tracking Column Names
        public static string COLUMN_APP_ACTIVITY_Date_Added = "Date_Added";
        public static string COLUMN_APP_ACTIVITY_Emp_ID = "Emp_ID";
        public static string COLUMN_APP_ACTIVITY_ID = "ID";
        public static string COLUMN_APP_ACTIVITY_Page_Name = "Page_Name";
        public static string COLUMN_APP_ACTIVITY_Page_Parameter = "Page_Parameter";
        public static string COLUMN_APP_ACTIVITY_URL = "URL";
        public static string COLUMN_APP_PREFERENCE_TYPE_Code = "Code";
        public static string COLUMN_APP_PREFERENCE_TYPE_Description = "Description";
        public static string COLUMN_APP_PREFERENCE_TYPE_ID = "ID";
        public static string COLUMN_APP_PREFERENCE_TYPE_Is_Active = "Is_Active";
        public static string COLUMN_APP_PREFERENCE_TYPE_Name = "Name";
        public static string COLUMN_APP_USER_PREFERENCE_App_Preference_Type_ID = "App_Preference_Type_ID";
        public static string COLUMN_APP_USER_PREFERENCE_Emp_ID = "Emp_ID";
        public static string COLUMN_APP_USER_PREFERENCE_ID = "ID";
        public static string COLUMN_APP_USER_PREFERENCE_Preference_Value = "Preference_Value";
        public static string COLUMN_ASSET_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_ASSET_Asset_Assignment_Type_ID = "Asset_Assignment_Type_ID";
        public static string COLUMN_ASSET_Asset_Condition_ID = "Asset_Condition_ID";
        public static string COLUMN_ASSET_Asset_Disposition_ID = "Asset_Disposition_ID";
        public static string COLUMN_ASSET_Asset_Type_ID = "Asset_Type_ID";
        public static string COLUMN_ASSET_Date_Added = "Date_Added";
        public static string COLUMN_ASSET_Date_Purchased = "Date_Purchased";
        public static string COLUMN_ASSET_ID = "ID";
        public static string COLUMN_ASSET_Is_Active = "Is_Active";
        public static string COLUMN_ASSET_Is_Leased = "Is_Leased";
        public static string COLUMN_ASSET_Leased_Term_Days = "Leased_Term_Days";
        public static string COLUMN_ASSET_Serial_Number = "Serial_Number";
        public static string COLUMN_ASSET_Tag_ID = "Tag_ID";
        public static string COLUMN_ASSET_Warranty_Term_Days = "Warranty_Term_Days";
        public static string COLUMN_ASSET_ATTACHMENT_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_ASSET_ATTACHMENT_Asset_ID = "Asset_ID";
        public static string COLUMN_ASSET_ATTACHMENT_Asset_Tamper_ID = "Asset_Tamper_ID";
        public static string COLUMN_ASSET_ATTACHMENT_Date_Added = "Date_Added";
        public static string COLUMN_ASSET_ATTACHMENT_Date_Modified = "Date_Modified";
        public static string COLUMN_ASSET_ATTACHMENT_Description = "Description";
        public static string COLUMN_ASSET_ATTACHMENT_File_Type_ID = "File_Type_ID";
        public static string COLUMN_ASSET_ATTACHMENT_ID = "ID";
        public static string COLUMN_ASSET_ATTACHMENT_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_ASSET_ATTACHMENT_Name = "Name";
        public static string COLUMN_ASSET_ATTACHMENT_Student_ID = "Student_ID";
        public static string COLUMN_ASSET_BIN_MAPPING_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_ASSET_BIN_MAPPING_Asset_ID = "Asset_ID";
        public static string COLUMN_ASSET_BIN_MAPPING_Bin_ID = "Bin_ID";
        public static string COLUMN_ASSET_BIN_MAPPING_Date_Added = "Date_Added";
        public static string COLUMN_ASSET_BIN_MAPPING_ID = "ID";
        public static string COLUMN_ASSET_CHECKOUT_EXCEPTION_STUDENT_DETAIL_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_ASSET_CHECKOUT_EXCEPTION_STUDENT_DETAIL_Asset_CheckOut_Exception_Student_Header_ID = "Asset_CheckOut_Exception_Student_Header_ID";
        public static string COLUMN_ASSET_CHECKOUT_EXCEPTION_STUDENT_DETAIL_Date_Added = "Date_Added";
        public static string COLUMN_ASSET_CHECKOUT_EXCEPTION_STUDENT_DETAIL_ID = "ID";
        public static string COLUMN_ASSET_CHECKOUT_EXCEPTION_STUDENT_DETAIL_Student_ID = "Student_ID";
        public static string COLUMN_ASSET_CHECKOUT_EXCEPTION_STUDENT_HEADER_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_ASSET_CHECKOUT_EXCEPTION_STUDENT_HEADER_Asset_Base_Type_ID = "Asset_Base_Type_ID";
        public static string COLUMN_ASSET_CHECKOUT_EXCEPTION_STUDENT_HEADER_Date_Added = "Date_Added";
        public static string COLUMN_ASSET_CHECKOUT_EXCEPTION_STUDENT_HEADER_Date_Modified = "Date_Modified";
        public static string COLUMN_ASSET_CHECKOUT_EXCEPTION_STUDENT_HEADER_Description = "Description";
        public static string COLUMN_ASSET_CHECKOUT_EXCEPTION_STUDENT_HEADER_ID = "ID";
        public static string COLUMN_ASSET_CHECKOUT_EXCEPTION_STUDENT_HEADER_Is_Active = "Is_Active";
        public static string COLUMN_ASSET_CHECKOUT_EXCEPTION_STUDENT_HEADER_Max_Check_Out_Override = "Max_Check_Out_Override";
        public static string COLUMN_ASSET_CHECKOUT_EXCEPTION_STUDENT_HEADER_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_ASSET_CHECKOUT_EXCEPTION_STUDENT_HEADER_Name = "Name";
        public static string COLUMN_ASSET_COMMENT_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_ASSET_COMMENT_Asset_ID = "Asset_ID";
        public static string COLUMN_ASSET_COMMENT_Comment = "Comment";
        public static string COLUMN_ASSET_COMMENT_Date_Added = "Date_Added";
        public static string COLUMN_ASSET_COMMENT_Date_Modified = "Date_Modified";
        public static string COLUMN_ASSET_COMMENT_ID = "ID";
        public static string COLUMN_ASSET_COMMENT_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_ASSET_LAW_ENFORCEMENT_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_ASSET_LAW_ENFORCEMENT_Asset_ID = "Asset_ID";
        public static string COLUMN_ASSET_LAW_ENFORCEMENT_Case_Number = "Case_Number";
        public static string COLUMN_ASSET_LAW_ENFORCEMENT_Comment = "Comment";
        public static string COLUMN_ASSET_LAW_ENFORCEMENT_Date_Added = "Date_Added";
        public static string COLUMN_ASSET_LAW_ENFORCEMENT_Date_Modified = "Date_Modified";
        public static string COLUMN_ASSET_LAW_ENFORCEMENT_Date_Picked_Up = "Date_Picked_Up";
        public static string COLUMN_ASSET_LAW_ENFORCEMENT_Date_Returned = "Date_Returned";
        public static string COLUMN_ASSET_LAW_ENFORCEMENT_ID = "ID";
        public static string COLUMN_ASSET_LAW_ENFORCEMENT_Law_Enforcement_Agency_ID = "Law_Enforcement_Agency_ID";
        public static string COLUMN_ASSET_LAW_ENFORCEMENT_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_ASSET_LAW_ENFORCEMENT_Officer_First_Name = "Officer_First_Name";
        public static string COLUMN_ASSET_LAW_ENFORCEMENT_Officer_Last_Name = "Officer_Last_Name";
        public static string COLUMN_ASSET_LAW_ENFORCEMENT_Received_By_Emp_ID = "Received_By_Emp_ID";
        public static string COLUMN_ASSET_LOAD_Added_By_Emp_Name = "Added_By_Emp_Name";
        public static string COLUMN_ASSET_LOAD_Added_By_EmpID = "Added_By_EmpID";
        public static string COLUMN_ASSET_LOAD_Asset_Base_Type_Desc = "Asset_Base_Type_Desc";
        public static string COLUMN_ASSET_LOAD_Asset_Base_Type_ID = "Asset_Base_Type_ID";
        public static string COLUMN_ASSET_LOAD_Asset_Type_Desc = "Asset_Type_Desc";
        public static string COLUMN_ASSET_LOAD_Asset_Type_ID = "Asset_Type_ID";
        public static string COLUMN_ASSET_LOAD_Comment = "Comment";
        public static string COLUMN_ASSET_LOAD_Date_Added = "Date_Added";
        public static string COLUMN_ASSET_LOAD_ID = "ID";
        public static string COLUMN_ASSET_LOAD_Is_Loaded = "Is_Loaded";
        public static string COLUMN_ASSET_LOAD_Purchased_Date = "Purchased_Date";
        public static string COLUMN_ASSET_LOAD_Serial_Number = "Serial_Number";
        public static string COLUMN_ASSET_LOAD_Site_Desc = "Site_Desc";
        public static string COLUMN_ASSET_LOAD_Site_ID = "Site_ID";
        public static string COLUMN_ASSET_LOAD_Tag_ID = "Tag_ID";
        public static string COLUMN_ASSET_REPAIR_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_ASSET_REPAIR_Asset_ID = "Asset_ID";
        public static string COLUMN_ASSET_REPAIR_Comment = "Comment";
        public static string COLUMN_ASSET_REPAIR_Date_Added = "Date_Added";
        public static string COLUMN_ASSET_REPAIR_Date_Modified = "Date_Modified";
        public static string COLUMN_ASSET_REPAIR_Date_Received = "Date_Received";
        public static string COLUMN_ASSET_REPAIR_Date_Sent = "Date_Sent";
        public static string COLUMN_ASSET_REPAIR_ID = "ID";
        public static string COLUMN_ASSET_REPAIR_Is_Leased = "Is_Leased";
        public static string COLUMN_ASSET_REPAIR_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_ASSET_REPAIR_Received_By_Emp_ID = "Received_By_Emp_ID";
        public static string COLUMN_ASSET_REPAIR_Received_Disposition_ID = "Received_Disposition_ID";
        public static string COLUMN_ASSET_REPAIR_Repair_Type_ID = "Repair_Type_ID";
        public static string COLUMN_ASSET_SEARCH_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_ASSET_SEARCH_Date_Added = "Date_Added";
        public static string COLUMN_ASSET_SEARCH_Date_Modified = "Date_Modified";
        public static string COLUMN_ASSET_SEARCH_Filter_Text = "Filter_Text";
        public static string COLUMN_ASSET_SEARCH_Filter_Value = "Filter_Value";
        public static string COLUMN_ASSET_SEARCH_ID = "ID";
        public static string COLUMN_ASSET_SEARCH_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_ASSET_SEARCH_DETAIL_Asset_ID = "Asset_ID";
        public static string COLUMN_ASSET_SEARCH_DETAIL_Asset_Search_ID = "Asset_Search_ID";
        public static string COLUMN_ASSET_SEARCH_DETAIL_Is_Checked = "Is_Checked";
        public static string COLUMN_ASSET_SEARCH_DETAIL_Is_Selected = "Is_Selected";
        public static string COLUMN_ASSET_SEARCH_DETAIL_Sort_Order = "Sort_Order";
        public static string COLUMN_ASSET_SITE_MAPPING_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_ASSET_SITE_MAPPING_Asset_ID = "Asset_ID";
        public static string COLUMN_ASSET_SITE_MAPPING_Date_Added = "Date_Added";
        public static string COLUMN_ASSET_SITE_MAPPING_ID = "ID";
        public static string COLUMN_ASSET_SITE_MAPPING_Site_ID = "Site_ID";
        public static string COLUMN_ASSET_SITE_STORED_MAPPING_Asset_ID = "Asset_ID";
        public static string COLUMN_ASSET_SITE_STORED_MAPPING_Asset_Site_ID = "Asset_Site_ID";
        public static string COLUMN_ASSET_SITE_STORED_MAPPING_Date_Modified = "Date_Modified";
        public static string COLUMN_ASSET_SITE_STORED_MAPPING_Emp_ID = "Emp_ID";
        public static string COLUMN_ASSET_SITE_STORED_MAPPING_ID = "ID";
        public static string COLUMN_ASSET_SITE_STORED_MAPPING_Stored_Site_ID = "Stored_Site_ID";
        public static string COLUMN_ASSET_STUDENT_FEE_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_ASSET_STUDENT_FEE_Asset_Base_Type_ID = "Asset_Base_Type_ID";
        public static string COLUMN_ASSET_STUDENT_FEE_Asset_Disposition_Desc = "Asset_Disposition_Desc";
        public static string COLUMN_ASSET_STUDENT_FEE_Asset_Disposition_ID = "Asset_Disposition_ID";
        public static string COLUMN_ASSET_STUDENT_FEE_Asset_ID = "Asset_ID";
        public static string COLUMN_ASSET_STUDENT_FEE_Asset_Student_Transaction_ID = "Asset_Student_Transaction_ID";
        public static string COLUMN_ASSET_STUDENT_FEE_Asset_Type_ID = "Asset_Type_ID";
        public static string COLUMN_ASSET_STUDENT_FEE_Comment = "Comment";
        public static string COLUMN_ASSET_STUDENT_FEE_Date_Added = "Date_Added";
        public static string COLUMN_ASSET_STUDENT_FEE_Date_Modified = "Date_Modified";
        public static string COLUMN_ASSET_STUDENT_FEE_ID = "ID";
        public static string COLUMN_ASSET_STUDENT_FEE_Is_Police_Report_Provided = "Is_Police_Report_Provided";
        public static string COLUMN_ASSET_STUDENT_FEE_Is_Processed_Fee = "Is_Processed_Fee";
        public static string COLUMN_ASSET_STUDENT_FEE_Is_Processed_School_Msg = "Is_Processed_School_Msg";
        public static string COLUMN_ASSET_STUDENT_FEE_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_ASSET_STUDENT_FEE_Owed_Amount = "Owed_Amount";
        public static string COLUMN_ASSET_STUDENT_FEE_Student_Device_Coverage_ID = "Student_Device_Coverage_ID";
        public static string COLUMN_ASSET_STUDENT_FEE_Student_ID = "Student_ID";
        public static string COLUMN_ASSET_STUDENT_NOTIFICATION_Asset_ID = "Asset_ID";
        public static string COLUMN_ASSET_STUDENT_NOTIFICATION_Asset_Student_Transaction_ID = "Asset_Student_Transaction_ID";
        public static string COLUMN_ASSET_STUDENT_NOTIFICATION_Date_Sent = "Date_Sent";
        public static string COLUMN_ASSET_STUDENT_NOTIFICATION_ID = "ID";
        public static string COLUMN_ASSET_STUDENT_NOTIFICATION_Notification_Type_ID = "Notification_Type_ID";
        public static string COLUMN_ASSET_STUDENT_NOTIFICATION_Sent_To = "Sent_To";
        public static string COLUMN_ASSET_STUDENT_NOTIFICATION_Student_ID = "Student_ID";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_Asset_ID = "Asset_ID";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_Check_In_Asset_Condition_ID = "Check_In_Asset_Condition_ID";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_Check_In_By_Emp_ID = "Check_In_By_Emp_ID";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_Check_In_Disposition_ID = "Check_In_Disposition_ID";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_Check_Out_Asset_Condition_ID = "Check_Out_Asset_Condition_ID";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_Check_Out_By_Emp_ID = "Check_Out_By_Emp_ID";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_Comment = "Comment";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_Date_Check_In = "Date_Check_In";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_Date_Check_Out = "Date_Check_Out";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_Found_Asset_Condition_ID = "Found_Asset_Condition_ID";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_Found_Date = "Found_Date";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_Found_Disposition_ID = "Found_Disposition_ID";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_ID = "ID";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_School_Year = "School_Year";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_Stu_Responsible_For_Damage = "Stu_Responsible_For_Damage";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_Student_ID = "Student_ID";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_Student_School_Number = "Student_School_Number";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_INTERACTION_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_INTERACTION_Asset_Student_Transaction_ID = "Asset_Student_Transaction_ID";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_INTERACTION_Comment = "Comment";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_INTERACTION_Date_Added = "Date_Added";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_INTERACTION_Date_Modified = "Date_Modified";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_INTERACTION_ID = "ID";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_INTERACTION_Interaction_Type_ID = "Interaction_Type_ID";
        public static string COLUMN_ASSET_STUDENT_TRANSACTION_INTERACTION_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_ASSET_TAMPER_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_ASSET_TAMPER_Asset_ID = "Asset_ID";
        public static string COLUMN_ASSET_TAMPER_Comment = "Comment";
        public static string COLUMN_ASSET_TAMPER_Date_Added = "Date_Added";
        public static string COLUMN_ASSET_TAMPER_Date_Modified = "Date_Modified";
        public static string COLUMN_ASSET_TAMPER_Date_Processed = "Date_Processed";
        public static string COLUMN_ASSET_TAMPER_ID = "ID";
        public static string COLUMN_ASSET_TAMPER_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_ASSET_TAMPER_Student_ID = "Student_ID";
        public static string COLUMN_ASSET_TEMP_DETAIL_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_ASSET_TEMP_DETAIL_Asset_Assignment_Type_ID = "Asset_Assignment_Type_ID";
        public static string COLUMN_ASSET_TEMP_DETAIL_Asset_Condition_ID = "Asset_Condition_ID";
        public static string COLUMN_ASSET_TEMP_DETAIL_Asset_Disposition_ID = "Asset_Disposition_ID";
        public static string COLUMN_ASSET_TEMP_DETAIL_Asset_Temp_Header_ID = "Asset_Temp_Header_ID";
        public static string COLUMN_ASSET_TEMP_DETAIL_Asset_Type_ID = "Asset_Type_ID";
        public static string COLUMN_ASSET_TEMP_DETAIL_Bin_ID = "Bin_ID";
        public static string COLUMN_ASSET_TEMP_DETAIL_Date_Added = "Date_Added";
        public static string COLUMN_ASSET_TEMP_DETAIL_Date_Purchased = "Date_Purchased";
        public static string COLUMN_ASSET_TEMP_DETAIL_ID = "ID";
        public static string COLUMN_ASSET_TEMP_DETAIL_Is_Leased = "Is_Leased";
        public static string COLUMN_ASSET_TEMP_DETAIL_Leased_Term_Days = "Leased_Term_Days";
        public static string COLUMN_ASSET_TEMP_DETAIL_Serial_Number = "Serial_Number";
        public static string COLUMN_ASSET_TEMP_DETAIL_Tag_ID = "Tag_ID";
        public static string COLUMN_ASSET_TEMP_DETAIL_Warranty_Term_Days = "Warranty_Term_Days";
        public static string COLUMN_ASSET_TEMP_HEADER_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_ASSET_TEMP_HEADER_Asset_Site_ID = "Asset_Site_ID";
        public static string COLUMN_ASSET_TEMP_HEADER_Date_Added = "Date_Added";
        public static string COLUMN_ASSET_TEMP_HEADER_Date_Modified = "Date_Modified";
        public static string COLUMN_ASSET_TEMP_HEADER_Date_Submit = "Date_Submit";
        public static string COLUMN_ASSET_TEMP_HEADER_Description = "Description";
        public static string COLUMN_ASSET_TEMP_HEADER_Has_Submit = "Has_Submit";
        public static string COLUMN_ASSET_TEMP_HEADER_ID = "ID";
        public static string COLUMN_ASSET_TEMP_HEADER_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_ASSET_TEMP_HEADER_Name = "Name";
        public static string COLUMN_ASSET_TEMP_HEADER_Submitted_By_Emp_ID = "Submitted_By_Emp_ID";
        public static string COLUMN_AUDIT_LOG_Column_Name = "Column_Name";
        public static string COLUMN_AUDIT_LOG_Column_Name_Desc = "Column_Name_Desc";
        public static string COLUMN_AUDIT_LOG_Date_Modified = "Date_Modified";
        public static string COLUMN_AUDIT_LOG_Emp_ID = "Emp_ID";
        public static string COLUMN_AUDIT_LOG_ID = "ID";
        public static string COLUMN_AUDIT_LOG_New_Value = "New_Value";
        public static string COLUMN_AUDIT_LOG_New_Value_Desc = "New_Value_Desc";
        public static string COLUMN_AUDIT_LOG_Old_Value = "Old_Value";
        public static string COLUMN_AUDIT_LOG_Old_Value_Desc = "Old_Value_Desc";
        public static string COLUMN_AUDIT_LOG_Primary_Key_ID = "Primary_Key_ID";
        public static string COLUMN_AUDIT_LOG_Table_Name = "Table_Name";
        public static string COLUMN_BIN_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_BIN_Capacity = "Capacity";
        public static string COLUMN_BIN_Date_Added = "Date_Added";
        public static string COLUMN_BIN_Date_Modified = "Date_Modified";
        public static string COLUMN_BIN_Description = "Description";
        public static string COLUMN_BIN_ID = "ID";
        public static string COLUMN_BIN_Is_Active = "Is_Active";
        public static string COLUMN_BIN_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_BIN_Number = "Number";
        public static string COLUMN_BIN_Site_ID = "Site_ID";
        public static string COLUMN_BUSINESS_RULE_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_BUSINESS_RULE_Code = "Code";
        public static string COLUMN_BUSINESS_RULE_Date_Added = "Date_Added";
        public static string COLUMN_BUSINESS_RULE_Date_Modified = "Date_Modified";
        public static string COLUMN_BUSINESS_RULE_Description = "Description";
        public static string COLUMN_BUSINESS_RULE_ID = "ID";
        public static string COLUMN_BUSINESS_RULE_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_BUSINESS_RULE_Name = "Name";
        public static string COLUMN_BUSINESS_RULE_Table_Name = "Table_Name";
        public static string COLUMN_BUSINESS_RULE_DETAIL_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_BUSINESS_RULE_DETAIL_Business_Rule_ID = "Business_Rule_ID";
        public static string COLUMN_BUSINESS_RULE_DETAIL_Code = "Code";
        public static string COLUMN_BUSINESS_RULE_DETAIL_Date_Added = "Date_Added";
        public static string COLUMN_BUSINESS_RULE_DETAIL_ID = "ID";
        public static string COLUMN_CT_ASSET_ASSIGNMENT_TYPE_Code = "Code";
        public static string COLUMN_CT_ASSET_ASSIGNMENT_TYPE_Description = "Description";
        public static string COLUMN_CT_ASSET_ASSIGNMENT_TYPE_ID = "ID";
        public static string COLUMN_CT_ASSET_ASSIGNMENT_TYPE_Is_Active = "Is_Active";
        public static string COLUMN_CT_ASSET_ASSIGNMENT_TYPE_Name = "Name";
        public static string COLUMN_CT_ASSET_BASE_TYPE_Code = "Code";
        public static string COLUMN_CT_ASSET_BASE_TYPE_Description = "Description";
        public static string COLUMN_CT_ASSET_BASE_TYPE_ID = "ID";
        public static string COLUMN_CT_ASSET_BASE_TYPE_Is_Active = "Is_Active";
        public static string COLUMN_CT_ASSET_BASE_TYPE_Max_Check_Out = "Max_Check_Out";
        public static string COLUMN_CT_ASSET_BASE_TYPE_Name = "Name";
        public static string COLUMN_CT_ASSET_CONDITION_Code = "Code";
        public static string COLUMN_CT_ASSET_CONDITION_Description = "Description";
        public static string COLUMN_CT_ASSET_CONDITION_ID = "ID";
        public static string COLUMN_CT_ASSET_CONDITION_Is_Active = "Is_Active";
        public static string COLUMN_CT_ASSET_CONDITION_Name = "Name";
        public static string COLUMN_CT_ASSET_DISPOSITION_Code = "Code";
        public static string COLUMN_CT_ASSET_DISPOSITION_Description = "Description";
        public static string COLUMN_CT_ASSET_DISPOSITION_Fixed_Asset_Disp_Code = "Fixed_Asset_Disp_Code";
        public static string COLUMN_CT_ASSET_DISPOSITION_Fixed_Asset_Disp_Desc = "Fixed_Asset_Disp_Desc";
        public static string COLUMN_CT_ASSET_DISPOSITION_ID = "ID";
        public static string COLUMN_CT_ASSET_DISPOSITION_Is_Active = "Is_Active";
        public static string COLUMN_CT_ASSET_DISPOSITION_Name = "Name";
        public static string COLUMN_CT_ASSET_TYPE_Asset_Base_Type_ID = "Asset_Base_Type_ID";
        public static string COLUMN_CT_ASSET_TYPE_Code = "Code";
        public static string COLUMN_CT_ASSET_TYPE_Description = "Description";
        public static string COLUMN_CT_ASSET_TYPE_ID = "ID";
        public static string COLUMN_CT_ASSET_TYPE_Is_Active = "Is_Active";
        public static string COLUMN_CT_ASSET_TYPE_Is_Serial_Req = "Is_Serial_Req";
        public static string COLUMN_CT_ASSET_TYPE_Is_Vendor_Req = "Is_Vendor_Req";
        public static string COLUMN_CT_ASSET_TYPE_Name = "Name";
        public static string COLUMN_CT_ASSET_TYPE_Vendor_ID = "Vendor_ID";
        public static string COLUMN_CT_CHECK_IN_TYPE_Code = "Code";
        public static string COLUMN_CT_CHECK_IN_TYPE_Description = "Description";
        public static string COLUMN_CT_CHECK_IN_TYPE_ID = "ID";
        public static string COLUMN_CT_CHECK_IN_TYPE_Is_Active = "Is_Active";
        public static string COLUMN_CT_CHECK_IN_TYPE_Name = "Name";
        public static string COLUMN_CT_DEVICE_FEE_TYPE_Code = "Code";
        public static string COLUMN_CT_DEVICE_FEE_TYPE_Description = "Description";
        public static string COLUMN_CT_DEVICE_FEE_TYPE_ID = "ID";
        public static string COLUMN_CT_DEVICE_FEE_TYPE_Is_Active = "Is_Active";
        public static string COLUMN_CT_DEVICE_FEE_TYPE_Name = "Name";
        public static string COLUMN_CT_FILE_TYPE_Code = "Code";
        public static string COLUMN_CT_FILE_TYPE_Description = "Description";
        public static string COLUMN_CT_FILE_TYPE_ID = "ID";
        public static string COLUMN_CT_FILE_TYPE_Is_Active = "Is_Active";
        public static string COLUMN_CT_FILE_TYPE_Name = "Name";
        public static string COLUMN_CT_INTERACTION_TYPE_Code = "Code";
        public static string COLUMN_CT_INTERACTION_TYPE_Description = "Description";
        public static string COLUMN_CT_INTERACTION_TYPE_ID = "ID";
        public static string COLUMN_CT_INTERACTION_TYPE_Is_Active = "Is_Active";
        public static string COLUMN_CT_INTERACTION_TYPE_Name = "Name";
        public static string COLUMN_CT_LAW_ENFORCEMENT_AGENCY_Code = "Code";
        public static string COLUMN_CT_LAW_ENFORCEMENT_AGENCY_Description = "Description";
        public static string COLUMN_CT_LAW_ENFORCEMENT_AGENCY_ID = "ID";
        public static string COLUMN_CT_LAW_ENFORCEMENT_AGENCY_Is_Active = "Is_Active";
        public static string COLUMN_CT_LAW_ENFORCEMENT_AGENCY_Name = "Name";
        public static string COLUMN_CT_LAW_ENFORCEMENT_AGENCY_Short_Name = "Short_Name";
        public static string COLUMN_CT_NOTIFICATION_TYPE_Code = "Code";
        public static string COLUMN_CT_NOTIFICATION_TYPE_Description = "Description";
        public static string COLUMN_CT_NOTIFICATION_TYPE_ID = "ID";
        public static string COLUMN_CT_NOTIFICATION_TYPE_Is_Active = "Is_Active";
        public static string COLUMN_CT_NOTIFICATION_TYPE_Name = "Name";
        public static string COLUMN_CT_REPAIR_TYPE_Code = "Code";
        public static string COLUMN_CT_REPAIR_TYPE_Description = "Description";
        public static string COLUMN_CT_REPAIR_TYPE_ID = "ID";
        public static string COLUMN_CT_REPAIR_TYPE_Is_Active = "Is_Active";
        public static string COLUMN_CT_REPAIR_TYPE_Name = "Name";
        public static string COLUMN_CT_SITE_Code = "Code";
        public static string COLUMN_CT_SITE_Description = "Description";
        public static string COLUMN_CT_SITE_Fixed_Asset_Loc_Description = "Fixed_Asset_Loc_Description";
        public static string COLUMN_CT_SITE_Fixed_Asset_Loc_Number = "Fixed_Asset_Loc_Number";
        public static string COLUMN_CT_SITE_ID = "ID";
        public static string COLUMN_CT_SITE_Is_Active = "Is_Active";
        public static string COLUMN_CT_SITE_Is_School_Site = "Is_School_Site";
        public static string COLUMN_CT_SITE_Name = "Name";
        public static string COLUMN_CT_SITE_Short_Name = "Short_Name";
        public static string COLUMN_CT_VENDOR_Code = "Code";
        public static string COLUMN_CT_VENDOR_Description = "Description";
        public static string COLUMN_CT_VENDOR_ID = "ID";
        public static string COLUMN_CT_VENDOR_Is_Active = "Is_Active";
        public static string COLUMN_CT_VENDOR_Name = "Name";
        public static string COLUMN_REPORTS_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_REPORTS_Date_Added = "Date_Added";
        public static string COLUMN_REPORTS_ID = "ID";
        public static string COLUMN_REPORTS_Is_Active = "Is_Active";
        public static string COLUMN_REPORTS_Report_Code = "Report_Code";
        public static string COLUMN_REPORTS_Report_Description = "Report_Description";
        public static string COLUMN_REPORTS_Report_Display_Name = "Report_Display_Name";
        public static string COLUMN_REPORTS_Report_Folder = "Report_Folder";
        public static string COLUMN_REPORTS_Report_Name = "Report_Name";
        public static string COLUMN_STUDENT_DEVICE_COVERAGE_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_STUDENT_DEVICE_COVERAGE_Date_Added = "Date_Added";
        public static string COLUMN_STUDENT_DEVICE_COVERAGE_Device_Fee_Type_ID = "Device_Fee_Type_ID";
        public static string COLUMN_STUDENT_DEVICE_COVERAGE_ID = "ID";
        public static string COLUMN_STUDENT_DEVICE_COVERAGE_Is_Active = "Is_Active";
        public static string COLUMN_STUDENT_DEVICE_COVERAGE_School_Year = "School_Year";
        public static string COLUMN_STUDENT_DEVICE_COVERAGE_Student_ID = "Student_ID";
        public static string COLUMN_STUDENT_DEVICE_FEE_SCHEDULE_Asset_Base_Type_ID = "Asset_Base_Type_ID";
        public static string COLUMN_STUDENT_DEVICE_FEE_SCHEDULE_Asset_Disposition_ID = "Asset_Disposition_ID";
        public static string COLUMN_STUDENT_DEVICE_FEE_SCHEDULE_Code = "Code";
        public static string COLUMN_STUDENT_DEVICE_FEE_SCHEDULE_Date_End = "Date_End";
        public static string COLUMN_STUDENT_DEVICE_FEE_SCHEDULE_Date_Start = "Date_Start";
        public static string COLUMN_STUDENT_DEVICE_FEE_SCHEDULE_Fee_Amount_With_Coverage = "Fee_Amount_With_Coverage";
        public static string COLUMN_STUDENT_DEVICE_FEE_SCHEDULE_Fee_Amount_Without_Coverage = "Fee_Amount_Without_Coverage";
        public static string COLUMN_STUDENT_DEVICE_FEE_SCHEDULE_ID = "ID";
        public static string COLUMN_SYSDIAGRAMS_definition = "definition";
        public static string COLUMN_SYSDIAGRAMS_diagram_id = "diagram_id";
        public static string COLUMN_SYSDIAGRAMS_name = "name";
        public static string COLUMN_SYSDIAGRAMS_principal_id = "principal_id";
        public static string COLUMN_SYSDIAGRAMS_version = "version";
        public static string COLUMN_V_ADD_ASSET_PREVIOUS_BATCH_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_V_ADD_ASSET_PREVIOUS_BATCH_Added_By_Emp_Name = "Added_By_Emp_Name";
        public static string COLUMN_V_ADD_ASSET_PREVIOUS_BATCH_Asset_Site_Code = "Asset_Site_Code";
        public static string COLUMN_V_ADD_ASSET_PREVIOUS_BATCH_Asset_Site_ID = "Asset_Site_ID";
        public static string COLUMN_V_ADD_ASSET_PREVIOUS_BATCH_Asset_Site_Name_Desc = "Asset_Site_Name_Desc";
        public static string COLUMN_V_ADD_ASSET_PREVIOUS_BATCH_Asset_Temp_Header_ID = "Asset_Temp_Header_ID";
        public static string COLUMN_V_ADD_ASSET_PREVIOUS_BATCH_Batch_Status = "Batch_Status";
        public static string COLUMN_V_ADD_ASSET_PREVIOUS_BATCH_Description = "Description";
        public static string COLUMN_V_ADD_ASSET_PREVIOUS_BATCH_Description_Short = "Description_Short";
        public static string COLUMN_V_ADD_ASSET_PREVIOUS_BATCH_Has_Been_Submitted = "Has_Been_Submitted";
        public static string COLUMN_V_ADD_ASSET_PREVIOUS_BATCH_Has_Submit = "Has_Submit";
        public static string COLUMN_V_ADD_ASSET_PREVIOUS_BATCH_Total_Asset = "Total_Asset";
        public static string COLUMN_V_ADD_ASSET_PREVIOUS_BATCH_Update_Date = "Update_Date";
        public static string COLUMN_V_ASSET_BIN_Asset_Condition_Desc = "Asset_Condition_Desc";
        public static string COLUMN_V_ASSET_BIN_Asset_Condition_ID = "Asset_Condition_ID";
        public static string COLUMN_V_ASSET_BIN_Asset_Disposition_Desc = "Asset_Disposition_Desc";
        public static string COLUMN_V_ASSET_BIN_Asset_Disposition_ID = "Asset_Disposition_ID";
        public static string COLUMN_V_ASSET_BIN_Asset_ID = "Asset_ID";
        public static string COLUMN_V_ASSET_BIN_Asset_Site_Code = "Asset_Site_Code";
        public static string COLUMN_V_ASSET_BIN_Asset_Site_Desc = "Asset_Site_Desc";
        public static string COLUMN_V_ASSET_BIN_Asset_Site_ID = "Asset_Site_ID";
        public static string COLUMN_V_ASSET_BIN_Asset_Type_Desc = "Asset_Type_Desc";
        public static string COLUMN_V_ASSET_BIN_Asset_Type_ID = "Asset_Type_ID";
        public static string COLUMN_V_ASSET_BIN_Bin_ID = "Bin_ID";
        public static string COLUMN_V_ASSET_BIN_Bin_Site_Code = "Bin_Site_Code";
        public static string COLUMN_V_ASSET_BIN_Bin_Site_Desc = "Bin_Site_Desc";
        public static string COLUMN_V_ASSET_BIN_Bin_Site_ID = "Bin_Site_ID";
        public static string COLUMN_V_ASSET_BIN_Tag_ID = "Tag_ID";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Asset_Base_Type_Desc = "Asset_Base_Type_Desc";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Asset_Base_Type_ID = "Asset_Base_Type_ID";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Asset_Disposition_Code = "Asset_Disposition_Code";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Asset_Disposition_Desc = "Asset_Disposition_Desc";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Asset_Disposition_ID = "Asset_Disposition_ID";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Asset_ID = "Asset_ID";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Asset_Site_Desc = "Asset_Site_Desc";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Asset_Site_ID = "Asset_Site_ID";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Asset_Student_Transaction_ID = "Asset_Student_Transaction_ID";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Asset_Type_Desc = "Asset_Type_Desc";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Asset_Type_ID = "Asset_Type_ID";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Check_Out_Asset_Condition_Desc = "Check_Out_Asset_Condition_Desc";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Check_Out_Asset_Condition_ID = "Check_Out_Asset_Condition_ID";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Date_Check_In = "Date_Check_In";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Date_Check_Out = "Date_Check_Out";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Date_Check_Out_Formatted = "Date_Check_Out_Formatted";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Disposition_Allow_CheckIn = "Disposition_Allow_CheckIn";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Disposition_Allow_CheckIn_Desc = "Disposition_Allow_CheckIn_Desc";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_School_Year = "School_Year";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Serial_Number = "Serial_Number";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Student_ID = "Student_ID";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Student_Name = "Student_Name";
        public static string COLUMN_V_ASSET_INFO_CHECKIN_Tag_ID = "Tag_ID";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Added_By_Emp_Name = "Added_By_Emp_Name";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Asset_ID = "Asset_ID";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Asset_Site_Code = "Asset_Site_Code";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Asset_Site_Desc = "Asset_Site_Desc";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Case_Number = "Case_Number";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Comment = "Comment";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Comment_Short = "Comment_Short";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Date_Picked_Up = "Date_Picked_Up";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Date_Picked_Up_Formatted = "Date_Picked_Up_Formatted";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Date_Returned = "Date_Returned";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Date_Returned_Formatted = "Date_Returned_Formatted";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_ID = "ID";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Law_Enforcement_Agency_ID = "Law_Enforcement_Agency_ID";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Law_Enforcement_Agency_Name = "Law_Enforcement_Agency_Name";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Law_Enforcement_Agency_Short_Name = "Law_Enforcement_Agency_Short_Name";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Modified_By_Emp_Name = "Modified_By_Emp_Name";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Officer_First_Name = "Officer_First_Name";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Officer_Full_Name = "Officer_Full_Name";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Officer_Last_Name = "Officer_Last_Name";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Received_By_Emp_ID = "Received_By_Emp_ID";
        public static string COLUMN_V_ASSET_LAW_ENFORCEMENT_Received_By_Emp_Name = "Received_By_Emp_Name";
        public static string COLUMN_V_ASSET_MASTER_LIST_Added_By_Emp_Desc = "Added_By_Emp_Desc";
        public static string COLUMN_V_ASSET_MASTER_LIST_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_V_ASSET_MASTER_LIST_Allow_Create_Repair = "Allow_Create_Repair";
        public static string COLUMN_V_ASSET_MASTER_LIST_Allow_Deadpool = "Allow_Deadpool";
        public static string COLUMN_V_ASSET_MASTER_LIST_Allow_Ewaste = "Allow_Ewaste";
        public static string COLUMN_V_ASSET_MASTER_LIST_Allow_Inactivate = "Allow_Inactivate";
        public static string COLUMN_V_ASSET_MASTER_LIST_Allow_Inactivate_Desc = "Allow_Inactivate_Desc";
        public static string COLUMN_V_ASSET_MASTER_LIST_Allow_Law_Enforcement = "Allow_Law_Enforcement";
        public static string COLUMN_V_ASSET_MASTER_LIST_Allow_Transfer = "Allow_Transfer";
        public static string COLUMN_V_ASSET_MASTER_LIST_Asset_Assignment_Type_Desc = "Asset_Assignment_Type_Desc";
        public static string COLUMN_V_ASSET_MASTER_LIST_Asset_Assignment_Type_ID = "Asset_Assignment_Type_ID";
        public static string COLUMN_V_ASSET_MASTER_LIST_Asset_Base_Type_Desc = "Asset_Base_Type_Desc";
        public static string COLUMN_V_ASSET_MASTER_LIST_Asset_Base_Type_ID = "Asset_Base_Type_ID";
        public static string COLUMN_V_ASSET_MASTER_LIST_Asset_Condition_Desc = "Asset_Condition_Desc";
        public static string COLUMN_V_ASSET_MASTER_LIST_Asset_Condition_ID = "Asset_Condition_ID";
        public static string COLUMN_V_ASSET_MASTER_LIST_Asset_Disposition_Desc = "Asset_Disposition_Desc";
        public static string COLUMN_V_ASSET_MASTER_LIST_Asset_Disposition_ID = "Asset_Disposition_ID";
        public static string COLUMN_V_ASSET_MASTER_LIST_Asset_ID = "Asset_ID";
        public static string COLUMN_V_ASSET_MASTER_LIST_Asset_Site_Code = "Asset_Site_Code";
        public static string COLUMN_V_ASSET_MASTER_LIST_Asset_Site_Desc = "Asset_Site_Desc";
        public static string COLUMN_V_ASSET_MASTER_LIST_Asset_Site_ID = "Asset_Site_ID";
        public static string COLUMN_V_ASSET_MASTER_LIST_Asset_Student_Transaction_ID = "Asset_Student_Transaction_ID";
        public static string COLUMN_V_ASSET_MASTER_LIST_Asset_Type_Desc = "Asset_Type_Desc";
        public static string COLUMN_V_ASSET_MASTER_LIST_Asset_Type_ID = "Asset_Type_ID";
        public static string COLUMN_V_ASSET_MASTER_LIST_Bin_Desc = "Bin_Desc";
        public static string COLUMN_V_ASSET_MASTER_LIST_Bin_ID = "Bin_ID";
        public static string COLUMN_V_ASSET_MASTER_LIST_Bin_Number = "Bin_Number";
        public static string COLUMN_V_ASSET_MASTER_LIST_Bin_Site_Desc = "Bin_Site_Desc";
        public static string COLUMN_V_ASSET_MASTER_LIST_Bin_Site_ID = "Bin_Site_ID";
        public static string COLUMN_V_ASSET_MASTER_LIST_Date_Added = "Date_Added";
        public static string COLUMN_V_ASSET_MASTER_LIST_Date_Check_In = "Date_Check_In";
        public static string COLUMN_V_ASSET_MASTER_LIST_Date_Purchased = "Date_Purchased";
        public static string COLUMN_V_ASSET_MASTER_LIST_Is_Active = "Is_Active";
        public static string COLUMN_V_ASSET_MASTER_LIST_Is_Active_Desc = "Is_Active_Desc";
        public static string COLUMN_V_ASSET_MASTER_LIST_Is_Leased = "Is_Leased";
        public static string COLUMN_V_ASSET_MASTER_LIST_Law_Enforcement_Count = "Law_Enforcement_Count";
        public static string COLUMN_V_ASSET_MASTER_LIST_Leased_ADP_Count = "Leased_ADP_Count";
        public static string COLUMN_V_ASSET_MASTER_LIST_Leased_Term_Date = "Leased_Term_Date";
        public static string COLUMN_V_ASSET_MASTER_LIST_Leased_Term_Date_Desc = "Leased_Term_Date_Desc";
        public static string COLUMN_V_ASSET_MASTER_LIST_Leased_Term_Days = "Leased_Term_Days";
        public static string COLUMN_V_ASSET_MASTER_LIST_Modified_By_Emp_Desc = "Modified_By_Emp_Desc";
        public static string COLUMN_V_ASSET_MASTER_LIST_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_V_ASSET_MASTER_LIST_Serial_Number = "Serial_Number";
        public static string COLUMN_V_ASSET_MASTER_LIST_Student_Assigned_To = "Student_Assigned_To";
        public static string COLUMN_V_ASSET_MASTER_LIST_Student_Assigned_To_And_ID = "Student_Assigned_To_And_ID";
        public static string COLUMN_V_ASSET_MASTER_LIST_Student_ID = "Student_ID";
        public static string COLUMN_V_ASSET_MASTER_LIST_Student_Name = "Student_Name";
        public static string COLUMN_V_ASSET_MASTER_LIST_Tag_ID = "Tag_ID";
        public static string COLUMN_V_ASSET_MASTER_LIST_Warranty_Term_Date = "Warranty_Term_Date";
        public static string COLUMN_V_ASSET_MASTER_LIST_Warranty_Term_Date_Desc = "Warranty_Term_Date_Desc";
        public static string COLUMN_V_ASSET_MASTER_LIST_Warranty_Term_Days = "Warranty_Term_Days";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Asset_Base_Type_Desc = "Asset_Base_Type_Desc";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Asset_Base_Type_ID = "Asset_Base_Type_ID";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Asset_Disposition_Desc = "Asset_Disposition_Desc";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Asset_Disposition_ID = "Asset_Disposition_ID";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Asset_ID = "Asset_ID";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Asset_Site_Desc = "Asset_Site_Desc";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Asset_Site_ID = "Asset_Site_ID";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Asset_Type_Desc = "Asset_Type_Desc";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Asset_Type_ID = "Asset_Type_ID";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Bin_ID = "Bin_ID";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Bin_Number = "Bin_Number";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Check_In_Asset_Condiction_Desc = "Check_In_Asset_Condiction_Desc";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Check_In_Asset_Condition_ID = "Check_In_Asset_Condition_ID";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Check_In_By_Emp_ID = "Check_In_By_Emp_ID";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Check_In_By_Emp_Name = "Check_In_By_Emp_Name";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Check_Out_Asset_Condition_Desc = "Check_Out_Asset_Condition_Desc";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Check_Out_Asset_Condition_ID = "Check_Out_Asset_Condition_ID";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Check_Out_By_Emp_ID = "Check_Out_By_Emp_ID";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Check_Out_By_Emp_Name = "Check_Out_By_Emp_Name";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Date_Check_In = "Date_Check_In";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Date_Check_In_Formatted = "Date_Check_In_Formatted";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Date_Check_Out = "Date_Check_Out";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Date_Check_Out_Formatted = "Date_Check_Out_Formatted";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_ID = "ID";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_School_Year = "School_Year";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Serial_Number = "Serial_Number";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Student_ID = "Student_ID";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Student_Name = "Student_Name";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Student_School_Name = "Student_School_Name";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Student_School_Number = "Student_School_Number";
        public static string COLUMN_V_ASSET_STUDENT_ASSGINMENT_Tag_ID = "Tag_ID";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Asset_ID = "Asset_ID";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Assigned_To_Student = "Assigned_To_Student";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Check_In_Asset_Condition_Desc = "Check_In_Asset_Condition_Desc";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Check_In_Asset_Condition_ID = "Check_In_Asset_Condition_ID";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Check_In_By_Emp_ID = "Check_In_By_Emp_ID";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Check_In_By_Emp_Name = "Check_In_By_Emp_Name";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Check_Out_Asset_Condition_Desc = "Check_Out_Asset_Condition_Desc";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Check_Out_Asset_Condition_ID = "Check_Out_Asset_Condition_ID";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Check_Out_By_Emp_ID = "Check_Out_By_Emp_ID";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Check_Out_By_Emp_Name = "Check_Out_By_Emp_Name";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Date_Check_In = "Date_Check_In";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Date_Check_In_Formatted = "Date_Check_In_Formatted";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Date_Check_Out = "Date_Check_Out";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Date_Check_Out_Formatted = "Date_Check_Out_Formatted";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_ID = "ID";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_School_Year = "School_Year";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Student_Check_Out_School = "Student_Check_Out_School";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Student_ID = "Student_ID";
        public static string COLUMN_V_ASSET_TAB_ASSGINMENT_Student_School_Number = "Student_School_Number";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_Added_By_Emp_Name = "Added_By_Emp_Name";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_Asset_ID = "Asset_ID";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_Asset_Site_Code = "Asset_Site_Code";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_Asset_Site_Desc = "Asset_Site_Desc";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_Asset_Site_ID = "Asset_Site_ID";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_Asset_Tamper_ID = "Asset_Tamper_ID";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_Date_Added = "Date_Added";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_Date_Added_Formatted = "Date_Added_Formatted";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_Date_Modified = "Date_Modified";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_Date_Modified_Formatted = "Date_Modified_Formatted";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_Description = "Description";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_File_Type_Desc = "File_Type_Desc";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_File_Type_ID = "File_Type_ID";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_ID = "ID";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_Is_Tampered_Attachment = "Is_Tampered_Attachment";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_Modified_By_Emp_Name = "Modified_By_Emp_Name";
        public static string COLUMN_V_ASSET_TAB_ATTACHMENTS_Name = "Name";
        public static string COLUMN_V_ASSET_TAB_CHANGES_Asset_ID = "Asset_ID";
        public static string COLUMN_V_ASSET_TAB_CHANGES_Column_Name = "Column_Name";
        public static string COLUMN_V_ASSET_TAB_CHANGES_Column_Name_Desc = "Column_Name_Desc";
        public static string COLUMN_V_ASSET_TAB_CHANGES_Date_Modified = "Date_Modified";
        public static string COLUMN_V_ASSET_TAB_CHANGES_Date_Modified_Formatted = "Date_Modified_Formatted";
        public static string COLUMN_V_ASSET_TAB_CHANGES_ID = "ID";
        public static string COLUMN_V_ASSET_TAB_CHANGES_Modified_By_Emp_Name = "Modified_By_Emp_Name";
        public static string COLUMN_V_ASSET_TAB_CHANGES_New_Value = "New_Value";
        public static string COLUMN_V_ASSET_TAB_CHANGES_New_Value_Desc = "New_Value_Desc";
        public static string COLUMN_V_ASSET_TAB_CHANGES_Old_Value = "Old_Value";
        public static string COLUMN_V_ASSET_TAB_CHANGES_Old_Value_Desc = "Old_Value_Desc";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_Added_By_Emp_Name = "Added_By_Emp_Name";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_Asset_ID = "Asset_ID";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_Asset_Site_Code = "Asset_Site_Code";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_Asset_Site_Desc = "Asset_Site_Desc";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_Asset_Site_ID = "Asset_Site_ID";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_Comment = "Comment";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_Comment_Short = "Comment_Short";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_Date_Added = "Date_Added";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_Date_Added_Formatted = "Date_Added_Formatted";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_Date_Modified = "Date_Modified";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_Date_Modified_Formatted = "Date_Modified_Formatted";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_ID = "ID";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_Modified_By_Emp_Name = "Modified_By_Emp_Name";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_Recent_Date = "Recent_Date";
        public static string COLUMN_V_ASSET_TAB_COMMENTS_Recent_Date_Formatted = "Recent_Date_Formatted";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Added_By_Emp_Name = "Added_By_Emp_Name";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Asset_ID = "Asset_ID";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Asset_Site_Code = "Asset_Site_Code";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Asset_Site_Desc = "Asset_Site_Desc";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Asset_Site_ID = "Asset_Site_ID";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Comment = "Comment";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Date_Added = "Date_Added";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Date_Added_Formatted = "Date_Added_Formatted";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Date_Modified = "Date_Modified";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Date_Modified_Formatted = "Date_Modified_Formatted";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Date_Received = "Date_Received";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Date_Received_Formatted = "Date_Received_Formatted";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Date_Sent = "Date_Sent";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Date_Sent_Formatted = "Date_Sent_Formatted";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_ID = "ID";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Modified_By_Emp_Name = "Modified_By_Emp_Name";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Received_By_Emp_ID = "Received_By_Emp_ID";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Received_By_Emp_Name = "Received_By_Emp_Name";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Repair_Type_Desc = "Repair_Type_Desc";
        public static string COLUMN_V_ASSET_TAB_REPAIRS_Repair_Type_ID = "Repair_Type_ID";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Added_By_Emp_Name = "Added_By_Emp_Name";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Asset_ID = "Asset_ID";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Asset_Site_Code = "Asset_Site_Code";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Asset_Site_Desc = "Asset_Site_Desc";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Comment = "Comment";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Comment_Short = "Comment_Short";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Date_Added = "Date_Added";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Date_Added_Formatted = "Date_Added_Formatted";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Date_Modified = "Date_Modified";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Date_Modified_Formatted = "Date_Modified_Formatted";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Date_Processed = "Date_Processed";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Has_Attachment = "Has_Attachment";
        public static string COLUMN_V_ASSET_TAB_TAMPER_ID = "ID";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Modified_By_Emp_Name = "Modified_By_Emp_Name";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Processed = "Processed";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Student_ID = "Student_ID";
        public static string COLUMN_V_ASSET_TAB_TAMPER_Student_Name = "Student_Name";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Asset_Condition_Name = "Asset_Condition_Name";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Asset_Disposition_Name = "Asset_Disposition_Name";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Asset_Type_Name = "Asset_Type_Name";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Bin_ID = "Bin_ID";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Bin_Number = "Bin_Number";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Date_Added = "Date_Added";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Date_Purchased = "Date_Purchased";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Date_Purchased_Formatted = "Date_Purchased_Formatted";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Detail_ID = "Detail_ID";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Group_Description = "Group_Description";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Group_Name = "Group_Name";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Has_Submit = "Has_Submit";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Header_ID = "Header_ID";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Is_Leased = "Is_Leased";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Leased_Term_Days = "Leased_Term_Days";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Serial_Number = "Serial_Number";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Site_Code = "Site_Code";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Site_Description = "Site_Description";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Tag_ID = "Tag_ID";
        public static string COLUMN_V_ASSET_TEMP_HEADER_DETAIL_Warranty_Term_Days = "Warranty_Term_Days";
        public static string COLUMN_V_BIN_Added_By_Emp_ID = "Added_By_Emp_ID";
        public static string COLUMN_V_BIN_Added_By_Emp_Name = "Added_By_Emp_Name";
        public static string COLUMN_V_BIN_Asset_Count = "Asset_Count";
        public static string COLUMN_V_BIN_Available_Capacity = "Available_Capacity";
        public static string COLUMN_V_BIN_bin_desc = "bin_desc";
        public static string COLUMN_V_BIN_Bin_Description = "Bin_Description";
        public static string COLUMN_V_BIN_Bin_Description_Short = "Bin_Description_Short";
        public static string COLUMN_V_BIN_Bin_ID = "Bin_ID";
        public static string COLUMN_V_BIN_Btn_Asset_Desc = "Btn_Asset_Desc";
        public static string COLUMN_V_BIN_Capacity = "Capacity";
        public static string COLUMN_V_BIN_Date_Added = "Date_Added";
        public static string COLUMN_V_BIN_Date_Added_Formatted = "Date_Added_Formatted";
        public static string COLUMN_V_BIN_Date_Modified = "Date_Modified";
        public static string COLUMN_V_BIN_Date_Modified_Formatted = "Date_Modified_Formatted";
        public static string COLUMN_V_BIN_Is_Active = "Is_Active";
        public static string COLUMN_V_BIN_Is_Active_Desc = "Is_Active_Desc";
        public static string COLUMN_V_BIN_Modified_By_Emp_ID = "Modified_By_Emp_ID";
        public static string COLUMN_V_BIN_Modified_By_Emp_Name = "Modified_By_Emp_Name";
        public static string COLUMN_V_BIN_Number = "Number";
        public static string COLUMN_V_BIN_Site_Code = "Site_Code";
        public static string COLUMN_V_BIN_Site_Description = "Site_Description";
        public static string COLUMN_V_BIN_Site_ID = "Site_ID";
        public static string COLUMN_V_BIN_Site_Name = "Site_Name";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Asset_Base_Type_Desc = "Asset_Base_Type_Desc";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Asset_Base_Type_ID = "Asset_Base_Type_ID";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Asset_Student_Transaction_ID = "Asset_Student_Transaction_ID";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Asset_Type_Desc = "Asset_Type_Desc";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Asset_Type_ID = "Asset_Type_ID";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Check_In_Asset_Condition_Desc = "Check_In_Asset_Condition_Desc";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Check_In_Asset_Condition_ID = "Check_In_Asset_Condition_ID";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Check_In_Asset_Disposition_Desc = "Check_In_Asset_Disposition_Desc";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Check_In_By_Emp_ID = "Check_In_By_Emp_ID";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Check_In_By_Emp_Name = "Check_In_By_Emp_Name";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Check_In_Disposition_ID = "Check_In_Disposition_ID";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Check_Out_Asset_Condition_Desc = "Check_Out_Asset_Condition_Desc";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Check_Out_Asset_Condition_ID = "Check_Out_Asset_Condition_ID";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Check_Out_By_Emp_ID = "Check_Out_By_Emp_ID";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Check_Out_By_Emp_Name = "Check_Out_By_Emp_Name";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Date_Check_In = "Date_Check_In";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Date_Check_In_Formatted = "Date_Check_In_Formatted";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Date_Check_Out = "Date_Check_Out";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Date_Check_Out_Formatted = "Date_Check_Out_Formatted";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Date_Found_Formatted = "Date_Found_Formatted";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Found_Asset_Condition_Desc = "Found_Asset_Condition_Desc";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Found_Asset_Disposition_Desc = "Found_Asset_Disposition_Desc";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Owed_Amount = "Owed_Amount";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Owes_Fee = "Owes_Fee";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_School_Year = "School_Year";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Student_Current_School = "Student_Current_School";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Student_Current_School_Desc = "Student_Current_School_Desc";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Student_ID = "Student_ID";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Student_Name = "Student_Name";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Student_School_Name = "Student_School_Name";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Student_School_Number = "Student_School_Number";
        public static string COLUMN_V_STUDENT_ASSET_SEARCH_Tag_ID = "Tag_ID";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Asset_Base_Type_Desc = "Asset_Base_Type_Desc";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Asset_Base_Type_ID = "Asset_Base_Type_ID";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Asset_Disposition_Desc = "Asset_Disposition_Desc";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Asset_Disposition_ID = "Asset_Disposition_ID";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Asset_ID = "Asset_ID";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Asset_Site_Desc = "Asset_Site_Desc";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Asset_Site_ID = "Asset_Site_ID";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Asset_Type_Desc = "Asset_Type_Desc";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Asset_Type_ID = "Asset_Type_ID";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Bin_ID = "Bin_ID";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Bin_Number = "Bin_Number";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Check_In_Asset_Condiction_Desc = "Check_In_Asset_Condiction_Desc";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Check_In_Asset_Condition_ID = "Check_In_Asset_Condition_ID";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Check_In_By_Emp_ID = "Check_In_By_Emp_ID";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Check_In_By_Emp_Name = "Check_In_By_Emp_Name";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Check_Out_Asset_Condition_Desc = "Check_Out_Asset_Condition_Desc";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Check_Out_Asset_Condition_ID = "Check_Out_Asset_Condition_ID";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Check_Out_By_Emp_ID = "Check_Out_By_Emp_ID";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Check_Out_By_Emp_Name = "Check_Out_By_Emp_Name";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Date_Check_In = "Date_Check_In";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Date_Check_Out = "Date_Check_Out";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Default_Disposition_Desc = "Default_Disposition_Desc";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Default_Disposition_ID = "Default_Disposition_ID";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Default_Interaction_Type_Desc = "Default_Interaction_Type_Desc";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Default_Interaction_Type_ID = "Default_Interaction_Type_ID";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_ID = "ID";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_School_Year = "School_Year";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Serial_Number = "Serial_Number";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Student_ID = "Student_ID";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Student_Name = "Student_Name";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Student_School_Name = "Student_School_Name";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Student_School_Number = "Student_School_Number";
        public static string COLUMN_V_STUDENT_CHECKIN_NO_TAG_ID_Tag_ID = "Tag_ID";
        public static string COLUMN_V_STUDENT_COVERAGE_Coverage_Type = "Coverage_Type";
        public static string COLUMN_V_STUDENT_COVERAGE_Is_Active = "Is_Active";
        public static string COLUMN_V_STUDENT_COVERAGE_School_Year = "School_Year";
        public static string COLUMN_V_STUDENT_COVERAGE_Student_ID = "Student_ID";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Asset_Base_Type_Desc = "Asset_Base_Type_Desc";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Asset_Base_Type_ID = "Asset_Base_Type_ID";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Asset_Disposition_Desc = "Asset_Disposition_Desc";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Asset_Disposition_ID = "Asset_Disposition_ID";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Asset_ID = "Asset_ID";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Asset_Site_Desc = "Asset_Site_Desc";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Asset_Site_ID = "Asset_Site_ID";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Asset_Type_Desc = "Asset_Type_Desc";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Asset_Type_ID = "Asset_Type_ID";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Bin_ID = "Bin_ID";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Bin_Number = "Bin_Number";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Check_In_Asset_Condiction_Desc = "Check_In_Asset_Condiction_Desc";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Check_In_Asset_Condition_ID = "Check_In_Asset_Condition_ID";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Check_In_By_Emp_ID = "Check_In_By_Emp_ID";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Check_In_By_Emp_Name = "Check_In_By_Emp_Name";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Check_Out_Asset_Condition_Desc = "Check_Out_Asset_Condition_Desc";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Check_Out_Asset_Condition_ID = "Check_Out_Asset_Condition_ID";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Check_Out_By_Emp_ID = "Check_Out_By_Emp_ID";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Check_Out_By_Emp_Name = "Check_Out_By_Emp_Name";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Date_Check_In = "Date_Check_In";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Date_Check_In_Formatted = "Date_Check_In_Formatted";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Date_Check_Out = "Date_Check_Out";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Date_Check_Out_Formatted = "Date_Check_Out_Formatted";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Disposition_Allow_CheckIn = "Disposition_Allow_CheckIn";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_ID = "ID";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_School_Year = "School_Year";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Serial_Number = "Serial_Number";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Student_ID = "Student_ID";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Student_Name = "Student_Name";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Student_School_Name = "Student_School_Name";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Student_School_Number = "Student_School_Number";
        public static string COLUMN_V_STUDENT_CURRENT_ASSIGNMENT_Tag_ID = "Tag_ID";
        public static string COLUMN_V_USER_SECURITY_INFO_AccessLevel = "AccessLevel";
        public static string COLUMN_V_USER_SECURITY_INFO_allsites = "allsites";
        public static string COLUMN_V_USER_SECURITY_INFO_App_ID = "App_ID";
        public static string COLUMN_V_USER_SECURITY_INFO_AppName = "AppName";
        public static string COLUMN_V_USER_SECURITY_INFO_ExpirationDate = "ExpirationDate";
        public static string COLUMN_V_USER_SECURITY_INFO_includedsites = "includedsites";
        public static string COLUMN_V_USER_SECURITY_INFO_Is_Security_Admin = "Is_Security_Admin";
        public static string COLUMN_V_USER_SECURITY_INFO_NetworkLogin = "NetworkLogin";
        public static string COLUMN_V_USER_SECURITY_INFO_RoleName = "RoleName";
        public static string COLUMN_V_USER_SECURITY_INFO_Sites_Access = "Sites_Access";
        public static string COLUMN_V_USER_SECURITY_INFO_User_Access_Site = "User_Access_Site";
        public static string COLUMN_V_USER_SECURITY_INFO_User_Access_Site_Desc = "User_Access_Site_Desc";
        #endregion

        //Stored Procedure Name
        #region Stored Proc Names

        //Add Asset Stored Proc
        public static string STORED_PROC_SP_GET_ADD_ASSET_TEMP_HEADER_DETAIL_INFO = "sp_Get_Add_Asset_Temp_Header_Detail_Info";

        //Insert App Activity
        public static string STORED_PROC_SP_INSERT_APP_ACTIVITY = "sp_Insert_App_Activity";

        //Insert Application Exception in security database
        public static string SECURITY_STORED_PROC_SP_INSERT_APPLICATION_EXCEPTIONS = "sp_Insert_ApplicationExceptions";

        //Insert Application Log
        public static string SECURITY_STORED_PROC_INSERT_APPLICATION_LOG_EVENT = "Insert_Application_Log_Event";

        //User Preference
        public static string STORED_PROC_SP_GET_USER_PREFERENCE_BY_TYPE = "sp_GetUserPreferenceByType";

        //Validation
        public static string STORED_PROC_SP_ASSET_TEMP_WITH_VALIDATION_MESSAGE  = "sp_Asset_Temp_With_Validation_Message";

        public static string STORED_PROC_SP_VALIDATE_STUDENT_CHECKOUT = "sp_Validate_Student_CheckOut";
        public static string STORED_PROC_SP_VALIDATE_ASSIGN_ASSET_TO_BIN = "sp_Validate_Assign_Asset_To_Bin";
        public static string STORED_PROC_SP_VALIDATE_DUPLICATE_ATTACHMENT_NAME = "sp_Validate_Duplicate_Attachment_Name";
        public static string STORED_PROC_SP_VALIDATE_DUPLICATE_TAG_ID_ON_EDIT = "sp_Validate_Duplicate_Tag_ID_On_Edit";
        public static string STORED_PROC_SP_VALIDATE_EDIT_ASSET = "sp_Validate_Edit_Asset";
        public static string STORED_PROC_SP_VALIDATE_ASSET_ON_SUBMIT_ADD = "sp_Validate_Asset_On_Submit_Add";
        public static string STORED_PROC_SP_VALIDATE_EDIT_ASSET_TEMP = "sp_Validate_Edit_Asset_Temp";
        public static string STORED_PROC_SP_VALIDATE_ON_ADD_ASSET_TO_TEMP = "sp_Validate_On_Add_Asset_To_Temp";
        public static string STORED_PROC_SP_VALIDATE_MASS_ASSIGN_ASSET_TO_BIN = "sp_Validate_Mass_Assign_Asset_To_Bin";
        
        public static string STORED_PROC_SP_STU_CHECK_IN = "sp_Stu_Check_In";
        public static string STORED_PROC_SP_STU_FOLLOW_UP = "sp_Stu_Follow_Up";
        public static string STORED_PROC_SP_STUDENT_CHECK_OUT = "sp_Student_Check_Out";
        public static string STORED_PROC_SP_STUDENT_CHECK_IN = "sp_Student_Check_In";
        public static string STORED_PROC_SP_STUDENT_CHECK_IN_UNIDENTIFIED = "sp_Student_Check_In_Unidentified";
        public static string STORED_PROC_SP_STUDENT_CHECK_IN_RESEARCH = "sp_Student_Check_In_Research";

        //Delete Stored Proc
        public static string STORED_PROC_DELETE_ASSET_TEMP_HEADER = "sp_Delete_Asset_Temp_Header";
        public static string STORED_PROC_DELETE_ASSET_TEMP_DETAIL = "sp_Delete_Asset_Temp_Detail";
        public static string STORED_PROC_DELETE_ASSET_ATTACHMENT = "sp_Delete_Asset_Attachment";
        public static string STORED_PROC_DELETE_ASSET_COMMENT = "sp_Delete_Asset_Comment";
        public static string STORED_PROC_DELETE_ASSET_REPAIR = "sp_Delete_Asset_Repair";
        public static string STORED_PROC_DELETE_ASSET_TAMPER = "sp_Delete_Asset_Tamper";
        public static string STORED_PROC_DELETE_ASSET_LAW_ENFORCEMENT = "sp_Delete_Asset_Law_Enforcement";

        //Update
        public static string STORED_PROC_UPDATE_ASSET_REPAIR_RECEIVED = "sp_Update_Asset_Repair_Received";
        public static string STORED_PROC_UPDATE_ASSET_SEARCH_DETAIL_CHECK = "sp_Update_Asset_Search_Detail_Check";
        public static string STORED_PROC_SP_UNASSIGN_ALL_BIN_ASSET_TEMP_DETAIL = "sp_Unassign_All_Bin_Asset_Temp_Detail";

        //Submit Asset Temp To Asset
        public static string STORED_PROC_SP_SUBMIT_ASSET_TEMP_TO_ASSET = "sp_Submit_Asset_Temp_To_Asset";
        //Application Exception on security.dbo.ApplicationException
        public static string STORED_PROC_SP_INSERT_APPLICATIONEXCEPTION = "sp_Insert_ApplicationExceptions";

        //Assign Asset to Bin
        public static string STORED_PROC_SP_ASSIGN_ASSET_TO_BIN = "sp_Assign_Asset_To_Bin";
        public static string STORED_PROC_SP_ASSIGN_ASSET_TO_BIN_MASS_FROM_ASSET_SEARCH = "sp_Assign_Asset_To_Bin_Mass_From_Asset_Search";

        //Transfer Asset
        public static string STORED_PROC_SP_TRANSFER_ASSET = "sp_Transfer_Asset";

        //Upsert
        public static string STORED_PROC_SP_UPSERT_ASSET = "sp_Upsert_Asset";
        public static string STORED_PROC_SP_UPSERT_ASSET_AUDIT_LOG = "sp_Upsert_Asset_Audit_Log";
        public static string STORED_PROC_SP_UPSERT_ASSET_BIN_MAPPING = "sp_Upsert_Asset_Bin_Mapping";
        public static string STORED_PROC_SP_UPSERT_ASSET_BIN_MAPPING_AUDIT_LOG = "sp_Upsert_Asset_Bin_Mapping_Audit_Log";
        public static string STORED_PROC_SP_UPSERT_ASSET_SEARCH = "sp_Upsert_Asset_Search";
        public static string STORED_PROC_SP_UPSERT_ASSET_SITE_MAPPING = "sp_Upsert_Asset_Site_Mapping";
        public static string STORED_PROC_SP_UPSERT_ASSET_SITE_MAPPING_AUDIT_LOG = "sp_Upsert_Asset_Site_Mapping_Audit_Log";
        public static string STORED_PROC_SP_UPSERT_ASSET_TAMPER = "sp_Upsert_Asset_Tamper";
        public static string STORED_PROC_SP_UPSERT_ASSET_TEMP_DETAIL = "sp_Upsert_Asset_Temp_Detail";
        public static string STORED_PROC_SP_UPSERT_ASSET_TEMP_HEADER = "sp_Upsert_Asset_Temp_Header";
        public static string STORED_PROC_SP_UPSERT_BIN = "sp_Upsert_Bin";
        public static string STORED_PROC_SP_UPSERT_CT_ASSET_ASSIGNMENT_TYPE = "sp_Upsert_CT_Asset_Assignment_Type";
        public static string STORED_PROC_SP_UPSERT_CT_ASSET_CONDITION = "sp_Upsert_CT_Asset_Condition";
        public static string STORED_PROC_SP_UPSERT_CT_ASSET_DISPOSITION = "sp_Upsert_CT_Asset_Disposition";
        public static string STORED_PROC_SP_UPSERT_CT_ASSET_TYPE = "sp_Upsert_CT_Asset_Type";
        public static string STORED_PROC_SP_UPSERT_CT_ASSET_TYPE_FEE_SCHEDULE = "sp_Upsert_CT_Asset_Type_Fee_Schedule";
        public static string STORED_PROC_SP_UPSERT_CT_DEVICE_FEE_TYPE = "sp_Upsert_CT_Device_Fee_Type";
        public static string STORED_PROC_SP_UPSERT_CT_FEE_TYPE = "sp_Upsert_CT_Fee_Type";
        public static string STORED_PROC_SP_UPSERT_CT_FILE_TYPE = "sp_Upsert_CT_File_Type";
        public static string STORED_PROC_SP_UPSERT_CT_INTERACTION_TYPE = "sp_Upsert_CT_Interaction_Type";
        public static string STORED_PROC_SP_UPSERT_CT_NOTIFICATION_TYPE = "sp_Upsert_CT_Notification_Type";
        public static string STORED_PROC_SP_UPSERT_CT_REPAIR_TYPE = "sp_Upsert_CT_Repair_Type";
        public static string STORED_PROC_SP_UPSERT_CT_SITE = "sp_Upsert_CT_Site";
        public static string STORED_PROC_SP_UPSERT_CT_VENDOR = "sp_Upsert_CT_Vendor";
        public static string STORED_PROC_SP_UPSERT_ASSET_ATTACHMENT = "sp_Upsert_Asset_Attachment";
        public static string STORED_PROC_SP_UPSERT_ASSET_COMMENT = "sp_Upsert_Asset_Comment";
        public static string STORED_PROC_SP_UPSERT_ASSET_LAW_ENFORCEMENT = "sp_Upsert_Asset_Law_Enforcement";
        public static string STORED_PROC_SP_UPSERT_ASSET_REPAIR = "sp_Upsert_Asset_Repair";
        public static string STORED_PROC_SP_UPSERT_APP_USER_PREFERENCE = "sp_Upsert_App_User_Preference";


        #endregion

        //Database Views
        #region Database Views
        public const string DB_VIEW_ASSET_MASTER_LIST = "v_Asset_Master_List";
        public const string DB_VIEW_ASSET_TAB_ASSIGNMENT = "v_Asset_Tab_Assginment";
        public const string DB_VIEW_ASSET_TAB_ATTACHMENTS = "v_Asset_Tab_Attachments";
        public const string DB_VIEW_ASSET_TAB_CHANGES = "v_Asset_Tab_Changes";
        public const string DB_VIEW_ASSET_TAB_COMMENTS = "v_Asset_Tab_Comments";
        public const string DB_VIEW_ASSET_TAB_REPAIRS = "v_Asset_Tab_Repairs";
        public const string DB_VIEW_ASSET_TAB_TAMPER = "v_Asset_Tab_Tamper";
        public const string DB_VIEW_ASSET_TEMP_HEADER_DETAIL = "v_Asset_Temp_Header_Detail";
        public const string DB_VIEW_BIN = "v_Bin";
        public const string DB_VIEW_ASSET_BIN = "v_Asset_Bin";
        public const string DB_VIEW_STUDENT_ASSET_SEARCH = "v_Student_Asset_Search";
        public const string DB_VIEW_ASSET_STUDENT_ASSIGNMENT = "v_Asset_Student_Assginment";
        public const string DB_VIEW_ASSET_INFO_CHECKIN = "v_Asset_Info_CheckIn";
        public const string DB_VIEW_STUDENT_CHECKIN_NO_TAG_ID = "v_Student_CheckIn_No_Tag_ID";
        public const string DB_VIEW_ASSET_LAW_ENFORCEMENT = "v_Asset_Law_Enforcement";

        #endregion

        //Asset Search Filter Name
        #region Search Filter for the AssetSearchPage.aspx
        public static string SEARCH_FILTER_SHOW_HIDE_FILTER = "Show_Hide_Filter";
        public static string SEARCH_FILTER_ID_SEARCH_TYPE = "ID_Search_Type";
        public static string SEARCH_FILTER_ID_LIST = "ID_List";
        public static string SEARCH_FILTER_SITE = "Site_ID";
        public static string SEARCH_FILTER_BIN_NUMBER_START = "Bin_Number_Start";
        public static string SEARCH_FILTER_BIN_NUMBER_END = "Bin_Number_End";
        public static string SEARCH_FILTER_ASSET_BASE_TYPE = "Asset_Base_Type_ID";
        public static string SEARCH_FILTER_ASSET_TYPE = "Asset_Type_ID";
        public static string SEARCH_FILTER_ASSET_DISPOSITION = "Asset_Disposition_ID";
        public static string SEARCH_FILTER_ASSET_CONDITION = "Asset_Condition_ID";
        public static string SEARCH_FILTER_ASSET_UNASSIGN_TO_BIN = "Asset_Unassign_To_Bin";
        public static string SEARCH_FILTER_PURCHASE_START_DATE = "Purchase_Start_Date";
        public static string SEARCH_FILTER_PURCHASE_END_DATE = "Purchase_End_Date";
        public static string SEARCH_FILTER_ADDED_BY_EMP = "Added_By_Emp_ID";
        public static string SEARCH_FILTER_MODIFIED_BY_EMP = "Modified_By_Emp_ID";

        public static string SEARCH_TYPE_TAG_ID = "TAGID";
        public static string SEARCH_TYPE_SERIAL_NUMBER = "SERNUM";
        public static string SEARCH_TYPE_STUDENT_ID = "STUID";
        #endregion

        //Tab Name for View Asset
        public const string VIEW_ASSET_TAB_ASSIGNMENTS = "Assignments";
        public const string VIEW_ASSET_TAB_ATTACHMENT = "Attachment";
        public const string VIEW_ASSET_TAB_COMMENTS = "Comments";
        public const string VIEW_ASSET_TAB_CHANGES = "Changes";
        public const string VIEW_ASSET_TAB_REPAIR = "Repair";
        public const string VIEW_ASSET_TAB_TAMPER = "Tamper";

        //Pages
        public const string PAGES_ACCESS_DENIED_PAGE = "/Pages/AccessDeniedPage.aspx";
        public const string PAGES_ADD_ASSET_DETAIL_PAGE = "/Pages/AddAssetDetailPage.aspx";
        public const string PAGES_ADD_ASSET_PAGE = "/Pages/AddAssetPage.aspx";
        public const string PAGES_ADD_ASSET_UPLOAD_PAGE = "/Pages/AddAssetUploadPage.aspx";
        public const string PAGES_ADD_BIN_PAGE = "/Pages/AddBinPage.aspx";
        public const string PAGES_ASSET_FOLLOW_UP_PAGE = "/Pages/AssetFollowUpPage.aspx";
        public const string PAGES_ASSET_SEARCH_PAGE = "/Pages/AssetSearchPage.aspx";
        public const string PAGES_CHECK_IN_ASSET_PAGE = "/Pages/CheckInAssetPage.aspx";
        public const string PAGES_CHECK_OUT_ASSET_PAGE = "/Pages/CheckOutAssetPage.aspx";
        public const string PAGES_ERROR_PAGE = "/Pages/ErrorPage.aspx";
        public const string PAGES_HOME_PAGE = "/Pages/HomePage.aspx";
        public const string PAGES_LOST_STOLEN_ASSET_PAGE = "/Pages/LostStolenAssetPage.aspx";
        public const string PAGES_MANAGE_ASSET_PROPERTIES_PAGE = "/Pages/ManageAssetPropertiesPage.aspx";
        public const string PAGES_STUDENT_SEARCH_PAGE = "/Pages/StudentSearchPage.aspx";
        public const string PAGES_TEST_PAGE = "/Pages/TestPage.aspx";
        public const string PAGES_APPLICATION_OFFLINE_PAGE = "/Pages/ApplicationOfflinePage.aspx";
        public const string PAGES_ASSET_REPORT_PAGE = "/Pages/AssetReportPage.aspx";

        //Disposition ID
        public const string DISP_ASSIGNED = "1";
        public const string DISP_STOLEN = "2";
        public const string DISP_RETURNED_TO_VENDOR = "3";
        public const string DISP_LOST = "4";
        public const string DISP_AVAILABLE = "5";
        public const string DISP_E_WASTE_WAREHOUSE = "7";
        public const string DISP_E_WASTE_PENDING = "8";
        public const string DISP_E_WASTE_RETURN_TO_VENDOR = "9";
        public const string DISP_FOUND = "10";
        public const string DISP_DONATED = "11";
        public const string DISP_DEAD_POOL = "12";
        public const string DISP_SENT_FOR_REPAIR = "13";
        public const string DISP_RESEARCH = "16";
        public const string DISP_UNIDENTIFIED = "17";
        public const string DISP_EVALUATE_CONDITION = "1004";
        public const string DISP_BROKEN = "1005";
        public const string DISP_REPLACED_WITH_ANOTHER_DEVICE = "1006";
        public const string DISP_INSURANCE_PAYMENT_RECEIVED = "1007";
        public const string DISP_LAW_ENFORCEMENT = "1008";

        //Business Rule
        public const string BUSINESS_RULE_DISPOSITION_ALLOW_INACTIVATE = "Disp_Allow_Inactivate";
        public const string BUSINESS_RULE_DISPOSITION_ALLOW_CHECKOUT = "Disp_Allow_CheckOut";
        public const string BUSINESS_RULE_DISPOSITION_ALLOW_CHECKIN = "Disp_Allow_CheckIn";
        public const string BUSINESS_RULE_DISPOSITION_ALLOW_TRANSFER = "Disp_Allow_Transfer";

        public const string BUSINESS_RULE_DISPOSITION_ALLOW_DEADPOOL = "Disp_Allow_Deadpool";
        public const string BUSINESS_RULE_DISPOSITION_ALLOW_EWASTE = "Disp_Allow_Ewaste";
        public const string BUSINESS_RULE_DISPOSITION_ALLOW_CREATE_REPAIR = "Disp_Allow_Create_Repair";
        public const string BUSINESS_RULE_DISPOSITION_AVAILABLE_RECEIVED_OWNED_ASSET = "Disp_Option_Avail_Received_Owned_Asset";
        public const string BUSINESS_RULE_DISPOSITION_AVAILABLE_RECEIVED_LEASED_ASSET = "Disp_Option_Avail_Received_Leased_Asset";

        public const string BUSINESS_RULE_DISPOSITION_NO_SITE_BIN_RESTRICTION = "Disp_No_Site_Bin_Restriction";
        public const string BUSINESS_RULE_DISPOSITION_CHECK_IN_STANDARD = "Disp_Option_Avail_CheckIn_Standard";
        public const string BUSINESS_RULE_DISPOSITION_CHECK_IN_STOLEN = "Disp_Option_Avail_CheckIn_Stolen";
        public const string BUSINESS_RULE_DISPOSITION_CHECK_IN_LOST = "Disp_Option_Avail_CheckIn_Lost";
        public const string BUSINESS_RULE_DISPOSITION_CHECK_IN_FOUND = "Disp_Option_Avail_CheckIn_Found";
        public const string BUSINESS_RULE_DISPOSITION_CHECK_IN_FOUND_SITE_MISMATCH = "Disp_Option_Avail_CheckIn_Found_Site_Mismatch";
        public const string BUSINESS_RULE_DISPOSITION_ADD_ASSET = "Disp_Option_Avail_Add_Asset";
        public const string BUSINESS_RULE_DISPOSITION_AVAILABLE_CHECK_IN_UNIDENTIFIED = "Disp_Option_Avail_Unidentified";
        public const string BUSINESS_RULE_DISPOSITION_AVAILABLE_RESEARCH = "Disp_Option_Avail_Research";
        public const string BUSINESS_RULE_DISPOSITION_AVAILABLE_LOST_STOLEN = "Disp_Option_Avail_Lost_Stolen";
        public const string BUSINESS_RULE_DISPOSITION_AVAILABLE_FOLLOW_UP_FILTER = "Disp_Option_Avail_Followup_Filter";

        public const string BUSINESS_RULE_DISPOSITION_AVAILABLE_FOLLOW_UP_EVALUATE_CONDITION = "Disp_Option_Avail_Followup_Evaluate_Condition";
        public const string BUSINESS_RULE_DISPOSITION_AVAILABLE_FOLLOW_UP_UNIDENTIFIED = "Disp_Option_Avail_Followup_Unidentified";
        public const string BUSINESS_RULE_DISPOSITION_AVAILABLE_FOLLOW_UP_RESEARCH = "Disp_Option_Avail_Followup_Research";

        public const string BUSINESS_RULE_REPAIR_TYPE_AVAILABLE_LEASED = "Repair_Type_Leased";
        public const string BUSINESS_RULE_REPAIR_TYPE_AVAILABLE_LEASED_ADP = "Repair_Type_Leased_ADP";
        public const string BUSINESS_RULE_REPAIR_TYPE_AVAILABLE_OWNED = "Repair_Type_Owned";


        public const string BUSINESS_RULE_CONDITION_AVAILABLE_ADD_ASSET = "Cond_Option_Avail_Add_Asset";
        public const string BUSINESS_RULE_CONDITION_AVAILABLE_CHECK_IN_DISP_BROKEN = "Cond_Option_Avail_CheckIn_Disp_Broken";
        public const string BUSINESS_RULE_CONDITION_AVAILABLE_CHECK_IN_STANDARD = "Cond_Option_Avail_CheckIn_Standard";
        public const string BUSINESS_RULE_CONDITION_AVAILABLE_CHECK_IN_FOUND = "Cond_Option_Avail_CheckIn_Found";
        public const string BUSINESS_RULE_CONDITION_AVAILABLE_CHECK_IN_UNIDENTIFIED = "Cond_Option_Avail_CheckIn_Unidentified";

        public const string BUSINESS_RULE_CONDITION_AVAILABLE_FOLLOW_UP = "Cond_Option_Avail_Follow_Up";
        public const string BUSINESS_RULE_CONDITION_AVAILABLE_FOLLOW_UP_BROKEN = "Cond_Option_Avail_Follow_Up_Broken";

        public const string BUSINESS_RULE_INTERACTION_TYPE_AVAILABLE_CHECK_IN_UNIDENTIFIED = "Inter_Type_Avail_Unidentified";

        //App Preference Type
        public const string APP_PREFERENCE_TYPE_Default_Site = "DEFAULT_SITE";

        //Check In Types
        public const string CHECK_IN_TYPE_CODE_STANDARD = "1";
        public const string CHECK_IN_TYPE_CODE_LOST = "2";
        public const string CHECK_IN_TYPE_CODE_STOLEN = "3";
        public const string CHECK_IN_TYPE_CODE_FOUND = "4";
        public const string CHECK_IN_TYPE_CODE_UNIDENTIFIED = "5";

        //Repair Type
        public const string REPAIR_TYPE_ACCIDENTAL = "1";
        public const string REPAIR_TYPE_WARRANTY = "2";

        //Base Type
        public const string CT_ASSET_BASE_TYPE_ID_Laptop = "1";
        public const string CT_ASSET_BASE_TYPE_ID_Power_Adapter = "2";

    }
}