USE Asset_Tracking

CREATE TABLE Asset_Site_Stored_Mapping
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Asset_ID INT NOT NULL,
	Asset_Site_ID INT NOT NULL,
	Stored_Site_ID INT NOT NULL,
	Emp_ID VARCHAR(11) NOT NULL,
	Date_Modified DATETIME NOT NULL
)