USE Asset_Tracking

CREATE TABLE Business_Rule_Detail
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Business_Rule_ID INT NOT NULL,
	Code VARCHAR(100) NOT NULL,
	Added_By_Emp_ID VARCHAR(11) NOT NULL,
	Date_Added DATETIME NOT NULL
)

