USE Asset_Tracking

CREATE TABLE Business_Rule
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Code VARCHAR(100) NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Description VARCHAR(1000) NULL,
	Table_Name VARCHAR(100) NULL,
	Added_By_Emp_ID VARCHAR(11) NOT NULL,
	Date_Added DATETIME NOT NULL,
	Modified_By_Emp_ID VARCHAR(11), 
	Date_Modified DATETIME
)

